### PR TITLE
Update

### PR DESCRIPTION
**Pull request by andriytyurnikov**
Role as ActiveSupport::Concern, and semantic version bump

### CODE REVIEW

**Comment by andriytyurnikov** [comment]
@cjbottaro - I don't know how to publish updated gem version. I guess `gem push` needs your credentials

**Comment by cjbottaro** [comment]
I can make you a gem owner.  What email should I use?

**Comment by andriytyurnikov** [comment]
Andriy.Tyurnikov@gmail.com

**Comment by cjbottaro** [comment]
Done.  You should be able to push to RubyGems now.

**Pull request merged**
