### PR TITLE
active_support/concern usage with/instead of schizo/role

### PR DESCRIPTION
**Pull request by andriytyurnikov**
here it is - support of ActiveSupport::Concern #11

### CODE REVIEW

**Comment by andriytyurnikov** [comment]
version bump?

**Comment by cjbottaro** [comment]
Done and released to Rubygems.

Btw, I'm going to make a 0.x branch and master will be used for 1.x.  I think I'm going to rewrite the whole thing (but keep all the current features)... :D

I want to use `DelegateClass` that way we don't have to mess with copy over instance variables.  Also, I think the code can be greatly simplified in general.

**Comment by andriytyurnikov** [comment]
Those are good news :)

Please consider deprecation or removal of Schizo::Role in 1.x :)

**Comment by cjbottaro** [comment]
`ActiveSupport` is a pretty heavy dependency.  I'd rather keep `Schizo::Role` so Schizo can be used with or without `ActiveSupport` / `Rails`.

**Comment by andriytyurnikov** [comment]
We could rewrite role to be same as concern

**Comment by cjbottaro** [comment]
Already done... :)  See latest commits on master. 

—

**Comment by andriytyurnikov** [comment]
awesome!
BTW, what is the state of master branch?

**Pull request merged**
